title: Default Page

options:
  changeTemplate: 
    editor: false
  changeTitle: 
    editor: false
  changeSlug:
    editor: false
  changeStatus:
    editor: false
  move: 
    editor: false
  delete:     
    editor: false
  sort:
    editor: false
  duplicate:
    editor: false

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      dateien:
        type: files


